# Generated by Django 2.0.2 on 2018-03-17 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animal', '0002_auto_20180316_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advert',
            name='category',
            field=models.IntegerField(choices=[[1, 'Все'], [2, 'Собаки'], [3, 'Щенки'], [4, 'Кошки'], [5, 'Котята']], default=1),
        ),
    ]
