# Generated by Django 2.0.2 on 2018-03-17 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animal', '0004_auto_20180317_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advert',
            name='category',
            field=models.IntegerField(choices=[(0, 'Все'), (1, 'Собаки'), (2, 'Щенки'), (3, 'Кошки'), (4, 'Котята')], default=0),
        ),
    ]
