# Generated by Django 2.0.2 on 2018-03-17 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animal', '0005_auto_20180317_1212'),
    ]

    operations = [
        migrations.AddField(
            model_name='advert',
            name='sex',
            field=models.IntegerField(choices=[(0, 'Все'), (1, 'Мальчик'), (2, 'Девочка')], default=0),
        ),
        migrations.AddField(
            model_name='advert',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
